---
- name: configuration
  hosts: all
  become: true
  vars:
    repofile: open_three-tier-app.repo

  tasks:
  - name: enable repos
    template:
      src: "{{repofile}}"
      dest: "/etc/yum.repos.d/{{repofile}}"
      mode: 0644

- name: deploy haproxy
  hosts: frontends
  become: true
  vars:
    packages: 
      - httpd
      - haproxy

  tasks:
  - name: Install packages
    package:
      name: "{{ item }}"
      state: latest
    with_items: "{{ packages }}"

  - name: configure haproxy
    template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    notify: restart HAproxy

  handlers:
  - name: restart HAproxy
    service:
      name: haproxy
      state: restarted
      enabled: true

- name: deploy tomcat
  hosts: apps
  gather_facts: false
  become: true
  vars:
    directories: 
      - "/usr/share/tomcat/webapps/ROOT"
      - "/usr/share/tomcat/webapps/ansible"

  tasks:
  - name: install tomcat
    package:
      name: tomcat
      state: latest

  - name: create ansible tomcat directories
    file:
      path: "{{ item }}"
      state: directory
    with_items: "{{ directories }}"

  - name: apply template to tomcat webapps/ROOT
    template:
      src: index.html.j2
      dest: "{{ item }}/index.html"
      mode: 0644
    with_items: "{{ directories }}"
    notify: start tomcat

  handlers:
  - name: start tomcat
    service:
      name: tomcat
      state: started
      enabled: true

- name: deploy postgres
  gather_facts: false
  become: true
  hosts: appdbs
  tasks:
  - name: install postgres
    yum:
      name: postgresql-server
      state: latest

  - name: initilize postgres only if it is not done
    command: postgresql-setup initdb
    args:
      creates: "/var/lib/pgsql/initdb.log"
    notify: start postgres
  handlers:
  - name: start postgres
    service:
      name: postgresql
      state: started
      enabled: true

- name: deploy apache
  hosts: apps
  gather_facts: false
  become: true
  hosts: apps
  tasks:
  - name: install apache
    yum:
      name: httpd
      state: latest
    notify: start apache

  handlers:
  - name: start apache
    service:
      name: httpd
      state: started
      enabled: true
