---
- name: Install packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages }}"

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart HAproxy
