- name: install tomcat
  package:
    name: tomcat
    state: latest

- name: create ansible tomcat directories
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ directories }}"

- name: apply template to tomcat webapps/ROOT
  template:
    src: index.html.j2
    dest: "{{ item }}/index.html"
    mode: 0644
  with_items: "{{ directories }}"
  notify: start tomcat

